{{- range concat .Values.providers .Values.extraProviders }}
{{- if and (not (eq (.enabled | toString) "false")) (not .roleArn) (.policy) }}
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Policy
metadata:
  name: {{ $.Values.environmentConfig.resourcePrefix }}-{{ .name }}
  labels:
    {{- include "crossplane-providers.labels" $ | nindent 4 }}
    crossplane.io/provider: {{ .name }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true  
spec:
  forProvider:
    policy: {{ .policy | quote }}
{{- end }}
{{- end }}
