apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: otlp-gateway-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: otlp-gateway
  updatePolicy:
    minReplicas: 3
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 100m
          memory: 512Mi
        maxAllowed:
          cpu: 500m
          memory: 3Gi
        controlledResources: ["cpu","memory"]
