{{- if .Values.crossplaneProvider.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-external-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: grafana-secretstore
    kind: SecretStore
  target:
    name: grafana-creds
    creationPolicy: Owner
    template:
      data:
        # TODO: move to helm chart so we can inject the URL
        instanceCredentials: '{"auth":"{{ `{{ .admin_user }}` }}:{{ `{{ .admin_password }}` }}","url":"{{ include "grafana.url" . }}"}'
        login: "{{ `{{ .admin_user }}` }}"
        password: "{{ `{{ .admin_password }}` }}"
        url: "{{ include "grafana.url" . }}"
  data:
    - secretKey: admin_user
      remoteRef:
        key: grafana
        property: admin-user
    - secretKey: admin_password
      remoteRef:
        key: grafana
        property: admin-password
{{- end }}