{{- if .Values.grafana.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: grafana-httproute
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  parentRefs:
    - name: {{ .Values.grafana.httpRoute.sharedGatewayName }}
      namespace: {{ .Values.grafana.httpRoute.sharedGatewayNamespace }}
  hostnames:
    - {{ .Values.grafana.httpRoute.host }}.{{ .Values.environmentConfig.clusterFqdn }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .Values.grafanaChart.releaseName }}
          port: 80
{{- end }}
