{{- if .Values.crossplaneProvider.enabled }}
apiVersion: orgmapper.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  grafanaUrl: "{{ include "grafana.url" . }}"
  credentials:
    source: Secret
    secretRef:
      name: grafana-provider-credentials
      namespace: {{ .Release.Namespace }}
      key: credentials
{{- end }}
