{{- if .Values.crossplaneProviders.grafana.enabled }}
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-grafana
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  package: xpkg.upbound.io/grafana/provider-grafana:v2.5.0
{{- end }}
