apiVersion: v2
name: crossplane-providers
description: A Helm chart for deploying Crossplane (AWS) providers with IRSA configuration
type: application
version: 0.0.26
# renovate: datasource=docker depName=crossplane-contrib/provider-family-aws registryUrl=https://xpkg.crossplane.io
appVersion: "v2.3.0"
maintainers:
  - name: Philips Software
keywords:
  - crossplane
  - aws
  - providers
  - irsa
