apiVersion: v2
name: fluent-bit-out-hsdp
description: Installs the Fluentbit HSP out plugin.
keywords:
  - logging
  - fluent-bit
  - fluentd
  - hsdp
version: 0.13.0
# renovate: datasource=docker depName=ghcr.io/philips-software/fluent-bit-out-hsdp
appVersion: 2.6.0
icon: https://fluentbit.io/images/logo.svg
home: https://github.com/philips-software/fluent-bit-out-hsdp
sources:
  - https://github.com/philips-software/fluent-bit-out-hsdp/
maintainers:
  - name: loafoe
    email: andy.loafoe@gmail.com
dependencies:
  - name: fluent-bit
    # renovate: datasource=helm depName=fluent-bit registryUrl=https://fluent.github.io/helm-charts
    version: 0.55.0
    repository: https://fluent.github.io/helm-charts
