apiVersion: v2
name: crossplane-functions
description: A Helm chart for deploying Crossplane functions
type: application
version: 0.0.11
maintainers:
  - name: Philips Software
keywords:
  - crossplane
  - aws
  - providers
  - irsa
