{{- if .Values.grafanaDatasource.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "masterdata-datasource.resourcePrefix" . }}-masterdata-grafana-ds-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: IgnoreExtraneous
  labels:
    {{- include "masterdata-datasource.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Placeholder - will be patched by the Job with actual password
  secureJsonData: '{"password":"PLACEHOLDER"}'
{{- end }}
